views.py
from flask import Blueprint, jsonify, render_template
from extensions import db
from models import build_model, build_clients
from models import Client, Onboard


bp = Blueprint('bp', __name__)

@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/compliance')
def compliance():
    return render_template('compliance.html', clients = Client.list_all_with_compliance_status())

@bp.route('/funnel')
def funnel():
    return render_template('funnel.html')

@bp.route('/gap_analysis')
def gap_analysis():
    return render_template('gap_analysis.html', clients = Client.list_all_with_document_status())

@bp.route('/kpi')
def kpi():
    return render_template('kpi.html', average_ttc = Onboard.compute_average())

@bp.route('/client_metric')
def client_metric():
    return render_template('client_metric.html')

@bp.route('/impact_analysis')
def impact_analysis():
    return render_template('impact_analysis.html')

@bp.route('/provenance')
def provenance():
    return render_template('provenance.html')

@bp.route('/build')
def build():
    
    db.graph.run("MATCH (n) DETACH DELETE n")
    
    m = build_model()

    return jsonify({'status': m})

@bp.route('/create_clients')
def create_clients():

    db.graph.run("match (n) detach delete n")

    m = build_clients()

    return jsonify({'status': m})

templates/basis.html
{% extends "bootstrap/base.html" %}
{% block title %}NeoFlask{% endblock %}

{% block navbar %}
<div class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{{ url_for('bp.index') }}">NeoFlask</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="{{ url_for('bp.index') }}">Home</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Portlets <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="{{ url_for('bp.compliance') }}">Compliance</a></li>
            <li><a href="{{ url_for('bp.funnel') }}">Funnel</a></li>
            <li><a href="{{ url_for('bp.gap_analysis') }}">Gap Analysis</a></li>
            <li><a href="{{ url_for('bp.kpi') }}">KPI's</a></li>
            <li><a href="{{ url_for('bp.client_metric') }}">Client Metrics</a></li>
            <li><a href="{{ url_for('bp.impact_analysis') }}">Impact Analysis</a></li>
            <li><a href="{{ url_for('bp.provenance') }}">Provenance</a></li>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="active"><a href="#">Log in <span class="sr-only"></span></a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container-fluid -->
</div>
{% endblock %}

{% block content %}
{% endblock %}

templates/client_metric.html
{% extends 'basis.html' %}

templates/compliance.html
{% extends 'basis.html' %}

{% block title %}Compliance{% endblock %}

{% block content %}
  <h1>Compliance</h1>
  <table class='table table-striped table-bordered'>
      <caption>Displays whether clients are in or out of compliance</caption>
      <thead>
          <tr>
              <th>Client ID</th>
              <th>Client Name</th>
              <th>Onboarding Complete</th>
              <th>Valid Compliance Workflow</th>
          </tr>
      </thead>
      <tbody>
          {% for result in clients %}
          <tr>
              <td>{{ result['client']['company_id'] }}</td>
              <td>{{ result['client']['company_name'] }}</td>
              <td>{{ result['completed'] }}</td>
              <td>{{ result['valid_onboard'] }}</td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
{% endblock %}

templates/funnel.html
{% extends 'basis.html' %}

templates/gap_analysis.html
{% extends 'basis.html' %}

{% block title %}Gap Analysis{% endblock %}

{% block content %}
  <h1>Gap Analysis</h1>
  <table class='table table-striped table-bordered'>
      <caption>Documents</caption>
      <thead>
          <tr>
              <th>Client ID</th>
              <th>Client Name</th>
              <th>Missing Document Type</th>
              <th>For Onboarding Step</th>
          </tr>
      </thead>
      <tbody>
          {% for result in clients %}
          <tr>
              <td>{{ result['client']['company_id']|title }}</td>
              <td>{{ result['client']['company_name']|title }}</td>
              <td>{{ result['document_type']|title }}</td>
              <td>{{ result['step_number']+1 }}</td>
          </tr>
          {% endfor %}
      </tbody>
  </table>
{% endblock %}

templates/impact_analysis.html
{% extends 'basis.html' %}

templates/index.html
{% extends 'basis.html' %}

{% block title %}
  Welcome
{% endblock %}

{% block content %}
  <h1>Welcome</h1>
{% endblock %}

templates/kpi.html
{% extends 'basis.html' %}

{% block content %}
<h1>Average Onboard</h1>
  <table class='table table-striped table-bordered'>
      <caption>Average Time to Completion of the Onboard</caption>
      <thead>
          <tr>
              <th>Average Time to Completion</th>
              <th>Time (Seconds)</th>
          </tr>
      </thead>
      <tbody>
          <tr>
              <td></td>
              <td>{{ average_ttc }}</td>
          </tr>
      </tbody>
  </table>
{% endblock %}

templates/provenance.html
{% extends 'basis.html' %}